// e46c3fd261d639a831722481db0207e8183df2bb2ca1bc825fe853fd61e4b777

require "../endpoint.idl"
require "../option.idl"

scope net::datagram
{
    interface Channel
    {
        in  setOption       (Option)            -> none;
        in  bind            (Endpoint)          -> none;

        in  localEndpoint   ()                  -> Endpoint;

        in  send            (bytes, Endpoint);
        out received        (bytes, Endpoint);
        out failed          (exception);

        in  close           ();
        out closed          ();
    }
}
