// e46c3fd261d639a831722481db0207e8183df2bb2ca1bc825fe853fd61e4b777

scope www::http
{
    scope header
    {
        //https://www.iana.org/assignments/http-fields/http-fields.xhtml permanent
        enum KeyRecognized
        {
            null,
            A_IM,
            Accept,
            Accept_Additions,
            Accept_CH,
            Accept_Datetime,
            Accept_Encoding,
            Accept_Features,
            Accept_Language,
            Accept_Patch,
            Accept_Post,
            Accept_Ranges,
            Accept_Signature,
            Access_Control_Allow_Credentials,
            Access_Control_Allow_Headers,
            Access_Control_Allow_Methods,
            Access_Control_Allow_Origin,
            Access_Control_Expose_Headers,
            Access_Control_Max_Age,
            Access_Control_Request_Headers,
            Access_Control_Request_Method,
            Age,
            Allow,
            ALPN,
            Alt_Svc,
            Alt_Used,
            Alternates,
            Apply_To_Redirect_Ref,
            Authentication_Control,
            Authentication_Info,
            Authorization,
            Available_Dictionary,
            Cache_Control,
            Cache_Status,
            Cal_Managed_ID,
            CalDAV_Timezones,
            Capsule_Protocol,
            CDN_Cache_Control,
            CDN_Loop,
            Cert_Not_After,
            Cert_Not_Before,
            Clear_Site_Data,
            Client_Cert,
            Client_Cert_Chain,
            Close,
            Concealed_Auth_Export,
            Connection,
            Content_Digest,
            Content_Disposition,
            Content_Encoding,
            Content_Language,
            Content_Length,
            Content_Location,
            Content_Range,
            Content_Security_Policy,
            Content_Security_Policy_Report_Only,
            Content_Type,
            Cookie,
            Cross_Origin_Embedder_Policy,
            Cross_Origin_Embedder_Policy_Report_Only,
            Cross_Origin_Opener_Policy,
            Cross_Origin_Opener_Policy_Report_Only,
            Cross_Origin_Resource_Policy,
            DASL,
            Date,
            DAV,
            Delta_Base,
            Deprecation,
            Depth,
            Destination,
            Dictionary_ID,
            DPoP,
            DPoP_Nonce,
            Early_Data,
            ETag,
            Expect,
            Expires,
            Forwarded,
            From,
            Hobareg,
            Host,
            If,
            If_Match,
            If_Modified_Since,
            If_None_Match,
            If_Range,
            If_Schedule_Tag_Match,
            If_Unmodified_Since,
            IM,
            Include_Referred_Token_Binding_ID,
            Keep_Alive,
            Label,
            Last_Event_ID,
            Last_Modified,
            Link,
            Link_Template,
            Location,
            Lock_Token,
            Max_Forwards,
            Memento_Datetime,
            Meter,
            MIME_Version,
            Negotiate,
            NEL,
            OData_EntityId,
            OData_Isolation,
            OData_MaxVersion,
            OData_Version,
            Optional_WWW_Authenticate,
            Ordering_Type,
            Origin,
            Origin_Agent_Cluster,
            OSCORE,
            OSLC_Core_Version,
            Overwrite,
            Ping_From,
            Ping_To,
            Position,
            Prefer,
            Preference_Applied,
            Priority,
            Proxy_Authenticate,
            Proxy_Authentication_Info,
            Proxy_Authorization,
            Proxy_Status,
            Public_Key_Pins,
            Public_Key_Pins_Report_Only,
            Range,
            Redirect_Ref,
            Referer,
            Referrer_Policy,
            Refresh,
            Replay_Nonce,
            Repr_Digest,
            Retry_After,
            Schedule_Reply,
            Schedule_Tag,
            Sec_Purpose,
            Sec_Token_Binding,
            Sec_WebSocket_Accept,
            Sec_WebSocket_Extensions,
            Sec_WebSocket_Key,
            Sec_WebSocket_Protocol,
            Sec_WebSocket_Version,
            Server,
            Server_Timing,
            Set_Cookie,
            Signature,
            Signature_Input,
            SLUG,
            SoapAction,
            Status_URI,
            Strict_Transport_Security,
            Sunset,
            TCN,
            TE,
            Timeout,
            Topic,
            Traceparent,
            Tracestate,
            Trailer,
            Transfer_Encoding,
            TTL,
            Upgrade,
            Urgency,
            Use_As_Dictionary,
            User_Agent,
            Variant_Vary,
            Vary,
            Via,
            Want_Content_Digest,
            Want_Repr_Digest,
            WWW_Authenticate,
            X_Content_Type_Options,
            X_Frame_Options,
        }
        alias KeyAny = string;
        alias Key = variant<KeyRecognized, KeyAny>;

        alias Value = string;
    }

    struct Header
    {
        header::Key   key;
        header::Value value;
    }
}
