/* This file is part of the the dci project. Copyright (C) 2013-2026 vopl, shtoba.
   This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public
   License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
   You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>. */

// e46c3fd261d639a831722481db0207e8183df2bb2ca1bc825fe853fd61e4b777
// b15a37183c32a03cae506ae094d1894df6baf99664684d8534c56d9acdecdccf

require "ppn/node/link/feature.idl"

scope ppn::service
{
    scope aup_legacy_since_2025_04 ~ aup
    {
        exception Error {}

        alias Oid = array<uint8, 32>;

        enum BlobStatus
        {
            present,
            missingAndWanted,
            missingAndUnwanted,
        }

        interface BlobTransfer
        {
            out statusChanged(BlobStatus);
            in getPiece(uint32 offset, uint32 size) -> tuple<BlobStatus, bytes>;
        }

        interface Supplier
        {
            in startBlobTransfer(Oid, BlobTransfer::Opposite);
        }

        interface SupplierCatalog : Supplier
        {
            in getReleases() -> set<Oid>;
            out newRelease(Oid);
        }

        interface SupplierStorage : Supplier
        {
        }
    }

    scope aup
    {
        exception Error {}

        interface BlobTransfer
        {
            out available();
            in getPiece(uint32 offset, uint32 size) -> opt<bytes>;
        }
    }

    scope aup
    {
        alias Oid = array<uint8, 32>;

        interface Supplier
        {
            out newRelease(Oid);
            in getReleases() -> set<Oid>;
            in startBlobTransfer(Oid, BlobTransfer::Opposite);
        }
    }

    interface Aup : node::link::Feature, node::link::feature::Payload {}
}
