/* This file is part of the the dci project. Copyright (C) 2013-2026 vopl, shtoba.
   This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public
   License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
   You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>. */

// e46c3fd261d639a831722481db0207e8183df2bb2ca1bc825fe853fd61e4b777
// b15a37183c32a03cae506ae094d1894df6baf99664684d8534c56d9acdecdccf

require "../error.idl"

scope www::http::client
{
    scope cookies
    {
        exception Error : http::Error {}

        enum SameSite
        {
            null,
            lax,
            strict,
            none,
        }

        scope entry
        {
            struct Id
            {
                string      name;
                bool        hostOnly;
                string      domain;
                string      path;
            }
        }

        struct Entry
        {
            entry::Id   id;

            string      value;

            bool        persistent;
            bool        secure;
            bool        httpOnly;
            bool        partitioned;
            SameSite    sameSite;

            uint64      creationTime;
            uint64      lastAccessTime;
            uint64      expiryTime;
        }

        scope store
        {
            interface Notifies
            {
                out added(list<Entry>);
                out changed(list<Entry>);
                out deleted(list<Entry>);
            }

            scope deserialization
            {
                exception TooSmall      : Error {}
                exception BadMagic      : Error {}
                exception BadCheck      : Error {}
                exception BadContent    : Error {}
            }
        }

        interface Store
        {
            in set(list<Entry>);
            in get(entry::Id) -> list<Entry>;
            in del(entry::Id);
            in expire(uint64 now, bool finalizeSession);
            in serialize() -> bytes;
            in deserialize(bytes) -> none;

            in watchNotifies(store::Notifies::Opposite);
        }

        interface IoGate
        {
            in fromResponse(
                string domain,
                string path,
                list<string>);

            in toRequest(
                string domain,
                string path,
                bool isSecure,
                bool isHttp) -> list<string>;
        }
    }

    interface Cookies
        : cookies::Store
        , cookies::IoGate
    {}
}
