// e46c3fd261d639a831722481db0207e8183df2bb2ca1bc825fe853fd61e4b777

require "message.idl"
require "../unreliable.idl"

scope www::ws
{
    interface Channel
        : Unreliable
    {
        out inputTxt(Message);
        out inputBin(Message);
        in outputTxt(Message);
        in outputBin(Message);
    }
}
