// e46c3fd261d639a831722481db0207e8183df2bb2ca1bc825fe853fd61e4b777

require "ppn/node/link/remote.idl"
require "rdb/feature.idl"

scope ppn::node::rdb
{
    interface Instance
    {
        in addRemote(link::Id, link::Remote);
    }

    interface Factory
    {
        in build(list<Feature> features) -> Instance;
    }

    exception Error {}
}

